import db from "./db";
import { creators, recipes } from "./schema";
import { createHash } from "crypto";

// Deterministic ID from title so IDs stay consistent across cold starts
function stableId(title: string): string {
  const hash = createHash("sha256").update(title).digest("hex");
  return [
    hash.slice(0, 8),
    hash.slice(8, 12),
    "4" + hash.slice(13, 16),
    hash.slice(16, 20),
    hash.slice(20, 32),
  ].join("-");
}

const SAMPLE_CREATORS = [
  {
    address: "0x1234567890abcdef1234567890abcdef12345678",
    name: "Chef Maria",
    bio: "Home cook from Oaxaca. Traditional Mexican recipes passed down three generations.",
    avatarUrl: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=200&h=200&fit=crop",
  },
  {
    address: "0xabcdefabcdefabcdefabcdefabcdefabcdefabcd",
    name: "Kenji Labs",
    bio: "Food scientist. I test recipes 50 times so you only have to cook them once.",
    avatarUrl: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=200&h=200&fit=crop",
  },
  {
    address: "0x9876543210fedcba9876543210fedcba98765432",
    name: "Naan Stop",
    bio: "Indian street food and comfort classics. Everything from scratch.",
    avatarUrl: "https://images.unsplash.com/photo-1566554273541-37a9ca77b91f?w=200&h=200&fit=crop",
  },
  {
    address: "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
    name: "Plant Power",
    bio: "100% vegan recipes that don't suck. No fake meat, just real food.",
    avatarUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=200&h=200&fit=crop",
  },
  {
    address: "0xcafebabecafebabecafebabecafebabecafebabe",
    name: "Pastry Punk",
    bio: "Punk rock baker. Sourdough obsessive. Croissant anarchist.",
    avatarUrl: "https://images.unsplash.com/photo-1556217477-d325251ece38?w=200&h=200&fit=crop",
  },
  {
    address: "0xa102a2cb8AAc6C7d2c477412Ebb7d41d0Ce53495",
    name: "Tyler",
    bio: "Software engineer who treats cooking like code. Precise, tested, no shortcuts.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
  },
];

const SAMPLE_RECIPES = [
  {
    creatorAddress: "0x1234567890abcdef1234567890abcdef12345678",
    title: "Mole Negro Oaxaqueno",
    description: "The king of moles. 30+ ingredients, 2 days of love. This is the recipe my grandmother refused to write down - until now.",
    imageUrl: "https://images.unsplash.com/photo-1615870216519-2f9fa575fa5c?w=800&h=600&fit=crop",
    price: 1.50,
    cuisine: "mexican",
    mealType: "dinner",
    dietaryTags: JSON.stringify(["gluten-free"]),
    prepTime: 120,
    cookTime: 180,
    servings: 8,
    difficulty: "hard",
    ingredients: JSON.stringify([
      "6 dried chilhuacle negro chiles",
      "4 dried mulato chiles",
      "3 dried pasilla chiles",
      "2 dried chipotle chiles",
      "1/2 cup sesame seeds",
      "1/4 cup raw almonds",
      "1/4 cup raw peanuts",
      "1 ripe plantain, sliced",
      "1 corn tortilla, torn",
      "4 whole cloves",
      "1 cinnamon stick",
      "1 tsp cumin seeds",
      "1 tsp oregano",
      "4 roma tomatoes",
      "1 white onion, quartered",
      "6 garlic cloves",
      "2 oz Mexican chocolate",
      "1 tbsp piloncillo or brown sugar",
      "Salt to taste",
      "Chicken or turkey for serving",
    ]),
    steps: JSON.stringify([
      "Toast all dried chiles on a comal until fragrant but not burnt. Remove stems and seeds. Soak in hot water for 30 minutes.",
      "In a dry skillet, toast sesame seeds, almonds, and peanuts separately until golden. Set aside.",
      "Fry the plantain slices and tortilla pieces in a little oil until dark brown. This adds color and sweetness.",
      "Toast cloves, cinnamon, cumin, and oregano in a dry pan for 1 minute.",
      "Char tomatoes, onion, and garlic on the comal until blackened on all sides.",
      "Blend the soaked chiles with a cup of their soaking liquid until very smooth. Strain through a fine sieve.",
      "Blend all toasted nuts, seeds, fried plantain, tortilla, and spices with the charred vegetables. Add liquid as needed.",
      "In a large heavy pot, heat oil and fry the chile puree, stirring constantly, for 15 minutes until it darkens.",
      "Add the nut-vegetable puree and cook another 15 minutes, stirring to prevent sticking.",
      "Add chocolate and piloncillo. Simmer on very low heat for at least 1 hour, adding broth as needed for consistency.",
      "Season with salt. The mole should coat the back of a spoon and taste complex - smoky, sweet, bitter, spicy.",
      "Serve over turkey or chicken with rice and fresh tortillas.",
    ]),
    notes: "This mole tastes even better the next day. Make a double batch and freeze half. The chile negro is essential - don't substitute.",
  },
  {
    creatorAddress: "0xabcdefabcdefabcdefabcdefabcdefabcdefabcd",
    title: "Science of the Perfect Smash Burger",
    description: "I tested 47 variations. This is the one. Crispy edges, juicy center, maximum Maillard reaction.",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=600&fit=crop",
    price: 0.50,
    cuisine: "american",
    mealType: "dinner",
    dietaryTags: JSON.stringify([]),
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: "easy",
    ingredients: JSON.stringify([
      "1 lb 80/20 ground beef (NOT leaner)",
      "4 Martin's potato rolls",
      "4 slices American cheese (yes, American)",
      "Kosher salt",
      "Fresh cracked black pepper",
      "1 tbsp butter",
      "Thinly sliced onion",
      "Pickles, ketchup, mustard for serving",
    ]),
    steps: JSON.stringify([
      "Divide beef into 4 equal balls (4oz each). Do NOT season yet. Do NOT overwork the meat.",
      "Heat a cast iron skillet or flat griddle to SCREAMING hot - 500F+. This is non-negotiable.",
      "Place a ball on the surface and IMMEDIATELY smash flat with a heavy spatula or burger press. You have 30 seconds before the proteins set.",
      "Season the top generously with kosher salt and pepper while the bottom sears.",
      "Cook undisturbed for 2-3 minutes until the edges are deeply browned and crispy. You want a crust.",
      "Flip once. Add cheese immediately. Cook 1 more minute.",
      "While burgers cook, butter and toast the potato rolls face-down in another pan.",
      "Assembly: bottom bun, burger, onion, pickles, sauce, top bun. Eat immediately.",
    ]),
    notes: "The 80/20 fat ratio is critical - leaner beef won't get that crispy crust. American cheese melts better than anything else for this application. I tested it. Fight me.",
  },
  {
    creatorAddress: "0x9876543210fedcba9876543210fedcba98765432",
    title: "Butter Chicken (Murgh Makhani)",
    description: "The real deal from Delhi, not the sugary cream sauce you get at most restaurants. Smoky, tangy, rich.",
    imageUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&h=600&fit=crop",
    price: 0.75,
    cuisine: "indian",
    mealType: "dinner",
    dietaryTags: JSON.stringify(["gluten-free"]),
    prepTime: 30,
    cookTime: 45,
    servings: 4,
    difficulty: "medium",
    ingredients: JSON.stringify([
      "1.5 lbs boneless chicken thighs",
      "1 cup full-fat yogurt",
      "2 tbsp lemon juice",
      "2 tsp Kashmiri chili powder",
      "1 tsp garam masala",
      "1 tsp turmeric",
      "Salt to taste",
      "3 tbsp butter",
      "1 tbsp oil",
      "1 large onion, finely diced",
      "4 cloves garlic, minced",
      "1 inch ginger, grated",
      "1 can (14oz) crushed tomatoes",
      "1 tsp sugar",
      "1 cup heavy cream",
      "2 tbsp kasuri methi (dried fenugreek leaves)",
      "Fresh cilantro for garnish",
    ]),
    steps: JSON.stringify([
      "Marinate chicken in yogurt, lemon juice, chili powder, garam masala, turmeric, and salt. Minimum 2 hours, overnight is better.",
      "Grill or broil marinated chicken until charred on edges. This char is what makes butter chicken taste like butter chicken.",
      "In a heavy pot, melt butter with oil. Saute onion until deeply golden (10+ minutes, don't rush this).",
      "Add garlic and ginger, cook 2 minutes until fragrant.",
      "Add crushed tomatoes and sugar. Simmer 15 minutes until oil separates from the sauce.",
      "Blend the sauce until completely smooth. Return to pot.",
      "Add cream and crushed kasuri methi (rub between your palms to release flavor).",
      "Cut grilled chicken into chunks and add to sauce. Simmer gently for 10 minutes.",
      "Adjust salt and finish with a knob of butter. Serve with naan or basmati rice.",
    ]),
    notes: "The yogurt marinade + charring step is what separates restaurant butter chicken from the stuff in a jar. Kasuri methi is the secret ingredient - find it at any Indian grocery store.",
  },
  {
    creatorAddress: "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
    title: "Crispy Sesame Tofu Bowl",
    description: "Shatteringly crispy tofu without deep frying. The cornstarch technique changes everything.",
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop",
    price: 0.25,
    cuisine: "japanese",
    mealType: "lunch",
    dietaryTags: JSON.stringify(["vegan", "dairy-free"]),
    prepTime: 20,
    cookTime: 25,
    servings: 2,
    difficulty: "easy",
    ingredients: JSON.stringify([
      "1 block extra-firm tofu, pressed and cubed",
      "3 tbsp cornstarch",
      "2 tbsp soy sauce",
      "1 tbsp rice vinegar",
      "1 tbsp maple syrup",
      "1 tsp sriracha",
      "1 tsp sesame oil",
      "2 tbsp vegetable oil",
      "2 cups cooked rice",
      "1 avocado, sliced",
      "1 cup edamame",
      "Shredded carrots and cucumber",
      "Sesame seeds and scallions for topping",
    ]),
    steps: JSON.stringify([
      "Press tofu for at least 15 minutes (wrap in paper towels, put something heavy on top). Cut into 3/4 inch cubes.",
      "Toss tofu cubes in cornstarch until every surface is coated. This is the secret to the crunch.",
      "Heat vegetable oil in a non-stick pan over medium-high heat. Add tofu in a single layer - don't crowd.",
      "Cook undisturbed 3-4 minutes per side until golden and crispy. Resist the urge to move them.",
      "Mix soy sauce, rice vinegar, maple syrup, sriracha, and sesame oil in a small bowl.",
      "Once tofu is crispy on all sides, pour sauce over and toss quickly. The sauce will sizzle and glaze the tofu.",
      "Build bowls: rice, crispy tofu, avocado, edamame, carrots, cucumber.",
      "Top with sesame seeds and sliced scallions.",
    ]),
    notes: "The cornstarch coating + hot pan + not moving the tofu = crunch city. Don't skip pressing the tofu or it'll steam instead of crisp.",
  },
  {
    creatorAddress: "0xcafebabecafebabecafebabecafebabecafebabe",
    title: "72-Hour Sourdough Focaccia",
    description: "Three days of fermentation. Olive oil pools. Salt crystals. This is the bread that broke my Instagram.",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&h=600&fit=crop",
    price: 1.00,
    cuisine: "italian",
    mealType: "snack",
    dietaryTags: JSON.stringify(["vegan", "dairy-free"]),
    prepTime: 30,
    cookTime: 25,
    servings: 8,
    difficulty: "medium",
    ingredients: JSON.stringify([
      "500g bread flour",
      "375g water (75% hydration)",
      "100g active sourdough starter",
      "10g salt",
      "Generous olive oil (the good stuff)",
      "Flaky sea salt (Maldon)",
      "Fresh rosemary",
      "Cherry tomatoes, halved (optional)",
      "Olives (optional)",
    ]),
    steps: JSON.stringify([
      "DAY 1: Mix flour, water, and starter. Let sit 30 minutes (autolyse). Add salt, fold to incorporate.",
      "Perform 4 sets of stretch-and-folds, 30 minutes apart. The dough should feel elastic and alive.",
      "Cover and let bulk ferment at room temp for 4-5 hours until doubled and jiggly.",
      "Transfer to an oiled container, cover tightly, and refrigerate for 48-72 hours. This is where the magic happens.",
      "DAY 3: Pour generous olive oil into a 9x13 pan. Transfer cold dough directly into the pan.",
      "Let the dough warm up and proof for 2-3 hours until it fills the pan and is puffy.",
      "Oil your fingers and dimple the entire surface, pressing all the way to the bottom.",
      "Top with rosemary, tomatoes, olives - whatever you want. Drizzle more olive oil. Sprinkle flaky salt.",
      "Bake at 450F for 22-25 minutes until deeply golden on top and crispy on the bottom.",
      "Let cool 10 minutes before cutting. Listen to the crackle.",
    ]),
    notes: "The 72-hour cold ferment develops insane flavor you can't get any other way. Don't rush it. Use the best olive oil you can afford - you'll taste it.",
  },
  {
    creatorAddress: "0x1234567890abcdef1234567890abcdef12345678",
    title: "Elote (Mexican Street Corn)",
    description: "Charred corn, creamy sauce, chile, lime. The best thing you'll eat standing on a sidewalk.",
    imageUrl: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800&h=600&fit=crop",
    price: 0.25,
    cuisine: "mexican",
    mealType: "snack",
    dietaryTags: JSON.stringify(["vegetarian", "gluten-free"]),
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: "easy",
    ingredients: JSON.stringify([
      "4 ears of corn, husked",
      "1/4 cup mayonnaise",
      "1/4 cup Mexican crema (or sour cream)",
      "1/2 cup cotija cheese, crumbled",
      "1 tsp chile piquin or Tajin",
      "2 limes",
      "Fresh cilantro, chopped",
      "Pinch of salt",
    ]),
    steps: JSON.stringify([
      "Grill corn directly over high heat, turning every 2-3 minutes until charred all around. You want black spots.",
      "Mix mayo and crema in a bowl until smooth.",
      "While corn is still hot, brush generously with the crema mixture.",
      "Roll in crumbled cotija cheese, pressing to stick.",
      "Sprinkle with chile powder, squeeze lime juice over everything.",
      "Top with cilantro and serve immediately.",
    ]),
    notes: "The char is everything. If you don't have a grill, broil the corn as close to the element as possible. Don't be shy with the lime.",
  },
  {
    creatorAddress: "0xabcdefabcdefabcdefabcdefabcdefabcdefabcd",
    title: "Reverse-Seared Ribeye Steak",
    description: "The thermodynamics of a perfect steak. Low oven, hot sear, chemistry does the rest.",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=600&fit=crop",
    price: 0.75,
    cuisine: "american",
    mealType: "dinner",
    dietaryTags: JSON.stringify(["gluten-free", "keto"]),
    prepTime: 10,
    cookTime: 60,
    servings: 2,
    difficulty: "medium",
    ingredients: JSON.stringify([
      "2 ribeye steaks, 1.5 inches thick",
      "Kosher salt",
      "Fresh cracked black pepper",
      "2 tbsp high smoke-point oil (avocado)",
      "3 tbsp butter",
      "4 garlic cloves, smashed",
      "Fresh thyme and rosemary sprigs",
    ]),
    steps: JSON.stringify([
      "Season steaks generously with salt and pepper. Place on a wire rack over a sheet pan.",
      "Put in a 250F oven. This is the reverse - low and slow first.",
      "Cook until internal temp hits 115F for medium-rare (about 45-50 minutes). Use a thermometer.",
      "Remove and let rest while you heat a cast iron skillet until it's smoking hot. Open a window.",
      "Add oil to the screaming hot pan. Place steaks and sear 1-1.5 minutes per side. Don't touch them.",
      "In the last 30 seconds, add butter, garlic, and herbs. Tilt the pan and baste the steaks with the foaming butter.",
      "Rest 5 minutes. The carryover will bring you to a perfect 130F medium-rare edge-to-edge.",
    ]),
    notes: "This method gives you edge-to-edge pink with a hard sear. Traditional searing gives you a grey band. The science: low oven dries the surface (better crust) while gently cooking the interior evenly.",
  },
  {
    creatorAddress: "0x9876543210fedcba9876543210fedcba98765432",
    title: "Pani Puri (Golgappa)",
    description: "Crispy hollow shells filled with spiced water. The most addictive street food on the planet.",
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&h=600&fit=crop",
    price: 0.50,
    cuisine: "indian",
    mealType: "snack",
    dietaryTags: JSON.stringify(["vegan", "dairy-free"]),
    prepTime: 45,
    cookTime: 30,
    servings: 6,
    difficulty: "hard",
    ingredients: JSON.stringify([
      "1 cup semolina (sooji/rava)",
      "1/4 cup all-purpose flour",
      "Water for dough",
      "Oil for deep frying",
      "For pani (spiced water):",
      "1 cup mint leaves",
      "1/2 cup cilantro",
      "2 green chiles",
      "1 inch ginger",
      "1 tsp cumin powder (roasted)",
      "1 tsp chaat masala",
      "1/2 tsp black salt",
      "Juice of 2 limes",
      "3 cups cold water",
      "For filling:",
      "1 cup boiled chickpeas",
      "2 boiled potatoes, finely diced",
      "1 small onion, finely diced",
      "Tamarind chutney",
    ]),
    steps: JSON.stringify([
      "Make the puris: Mix semolina, flour, and water to form a very stiff dough. Knead for 10 minutes until smooth.",
      "Rest dough 20 minutes covered. Roll extremely thin - almost translucent.",
      "Cut into 2-inch circles using a cookie cutter or glass.",
      "Heat oil to 375F. Fry puris - they should puff up into hollow balls within seconds. If they don't puff, oil isn't hot enough.",
      "Drain on paper towels. They should be completely hollow inside and shatteringly crispy.",
      "Make the pani: Blend mint, cilantro, chiles, ginger with 1 cup water until smooth.",
      "Strain and add remaining water, cumin, chaat masala, black salt, and lime juice. Taste - it should be tangy, spicy, refreshing.",
      "Chill the pani. It must be ice cold.",
      "To serve: Crack a hole in the top of each puri, add a spoonful of chickpea-potato filling, a drizzle of tamarind chutney.",
      "Fill with cold pani and eat IMMEDIATELY in one bite. The clock starts the moment the water goes in.",
    ]),
    notes: "The dough must be very stiff and rolled very thin for proper puffing. The pani must be freezing cold. And yes, you eat the whole thing in one bite - that's the point.",
  },
  {
    creatorAddress: "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
    title: "Thai Green Curry (Vegan)",
    description: "Rich, coconutty, spicy. You won't miss the fish sauce. Trust me on this one.",
    imageUrl: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&h=600&fit=crop",
    price: 0.50,
    cuisine: "thai",
    mealType: "dinner",
    dietaryTags: JSON.stringify(["vegan", "gluten-free", "dairy-free"]),
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: "medium",
    ingredients: JSON.stringify([
      "For curry paste (or use 3 tbsp store-bought):",
      "6 green Thai chiles",
      "4 cloves garlic",
      "2 shallots",
      "1 stalk lemongrass (tender part only)",
      "1 inch galangal or ginger",
      "1 tsp coriander seeds, toasted",
      "1 tsp cumin seeds, toasted",
      "Zest of 1 lime",
      "For curry:",
      "2 cans full-fat coconut milk",
      "2 tbsp soy sauce (replaces fish sauce)",
      "1 tbsp coconut sugar",
      "1 block firm tofu, cubed",
      "1 Japanese eggplant, sliced",
      "1 cup Thai basil leaves",
      "Bamboo shoots",
      "Kaffir lime leaves",
      "Jasmine rice for serving",
    ]),
    steps: JSON.stringify([
      "If making paste: blend all paste ingredients into a smooth paste with a splash of water. A mortar and pestle is traditional and better.",
      "Scoop the thick cream from the top of one can of coconut milk into a hot wok.",
      "Fry the curry paste in the coconut cream for 3-4 minutes until fragrant and the oil separates. This blooms the flavors.",
      "Add the remaining coconut milk, soy sauce, and coconut sugar. Bring to a simmer.",
      "Add eggplant and bamboo shoots. Cook 5 minutes until eggplant softens.",
      "Add tofu and torn kaffir lime leaves. Simmer 5 more minutes.",
      "Turn off heat. Stir in Thai basil - it wilts from residual heat.",
      "Serve over jasmine rice. Eat with a spoon.",
    ]),
    notes: "The trick to vegan Thai curry: soy sauce + coconut sugar replaces fish sauce surprisingly well. Frying the paste in coconut cream (not oil) is the technique that makes restaurant curry taste different from home curry.",
  },
  {
    creatorAddress: "0xcafebabecafebabecafebabecafebabecafebabe",
    title: "Brown Butter Chocolate Chip Cookies",
    description: "Chewy centers, crispy edges, toffee undertones from the brown butter. I retired all other cookie recipes.",
    imageUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&h=600&fit=crop",
    price: 0.50,
    cuisine: "american",
    mealType: "dessert",
    dietaryTags: JSON.stringify(["vegetarian"]),
    prepTime: 20,
    cookTime: 12,
    servings: 24,
    difficulty: "easy",
    ingredients: JSON.stringify([
      "2 sticks (1 cup) unsalted butter",
      "2 1/4 cups all-purpose flour",
      "1 tsp baking soda",
      "1 tsp salt",
      "1 cup dark brown sugar, packed",
      "1/2 cup granulated sugar",
      "2 large eggs + 1 yolk",
      "2 tsp vanilla extract",
      "2 cups dark chocolate chips or chunks",
      "Flaky sea salt for topping",
    ]),
    steps: JSON.stringify([
      "Brown the butter: Melt butter in a light-colored pan over medium heat. Swirl constantly. It'll foam, then turn golden with brown flecks and smell nutty. Remove immediately.",
      "Pour browned butter into a bowl and refrigerate 30 minutes until solid but scoopable (like softened butter consistency).",
      "Whisk flour, baking soda, and salt in a bowl. Set aside.",
      "Beat cooled brown butter with both sugars for 3 minutes until fluffy and lightened in color.",
      "Add eggs, extra yolk (this is the chewy secret), and vanilla. Beat until smooth.",
      "Fold in flour mixture until JUST combined. Overmixing = tough cookies.",
      "Fold in chocolate chips. The dough should be thick and smell incredible.",
      "Scoop into balls and refrigerate at least 24 hours (72 hours is better). This is mandatory, not optional.",
      "Bake at 375F for 10-12 minutes until edges are set but centers look underdone. They'll firm up as they cool.",
      "Sprinkle with flaky salt immediately out of the oven.",
    ]),
    notes: "The 24-72 hour rest hydrates the flour and concentrates flavors. I A/B tested fresh vs rested dough with 20 people. Rested won unanimously. Don't skip it.",
  },
  {
    creatorAddress: "0x9876543210fedcba9876543210fedcba98765432",
    title: "Dal Makhani",
    description: "The overnight dal that tastes like velvet. Black lentils simmered until they surrender.",
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&h=600&fit=crop",
    price: 0.75,
    cuisine: "indian",
    mealType: "dinner",
    dietaryTags: JSON.stringify(["vegetarian", "gluten-free"]),
    prepTime: 15,
    cookTime: 480,
    servings: 6,
    difficulty: "easy",
    ingredients: JSON.stringify([
      "1 cup whole black lentils (urad dal), soaked overnight",
      "1/4 cup kidney beans (rajma), soaked overnight",
      "4 cups water",
      "3 tbsp butter",
      "1 large onion, finely diced",
      "4 cloves garlic, minced",
      "1 inch ginger, grated",
      "1 can (14oz) crushed tomatoes",
      "1 tsp Kashmiri chili powder",
      "1 tsp garam masala",
      "1/2 cup heavy cream",
      "Salt to taste",
      "Fresh cilantro and butter for finishing",
    ]),
    steps: JSON.stringify([
      "Pressure cook soaked lentils and kidney beans in 4 cups water until completely soft (40 min in pressure cooker, or 2+ hours on stove).",
      "In a separate pan, melt butter. Saute onions until deeply golden brown, 15 minutes minimum.",
      "Add garlic and ginger, cook 2 minutes. Add tomatoes, chili powder, and garam masala.",
      "Cook the masala base until oil separates from the mixture, about 10 minutes.",
      "Add the masala to the cooked lentils. Add enough water for a creamy consistency.",
      "Here's the secret: simmer on the LOWEST possible heat for 4-6 hours, stirring occasionally. The lentils break down into velvet.",
      "In the last hour, add cream and adjust salt.",
      "Finish with a generous pat of butter and fresh cilantro.",
    ]),
    notes: "Real dal makhani cooks for hours - some restaurants simmer it overnight. The long cook is what transforms it from 'lentil soup' to something transcendent. A slow cooker on low works great.",
  },
  {
    creatorAddress: "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
    title: "Mushroom Bourguignon",
    description: "All the depth of beef bourguignon, zero animals. Red wine, herbs, and mushrooms doing the heavy lifting.",
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&h=600&fit=crop",
    price: 0.75,
    cuisine: "french",
    mealType: "dinner",
    dietaryTags: JSON.stringify(["vegan", "dairy-free"]),
    prepTime: 25,
    cookTime: 60,
    servings: 4,
    difficulty: "medium",
    ingredients: JSON.stringify([
      "1 lb mixed mushrooms (cremini, shiitake, oyster)",
      "2 large carrots, chunked",
      "1 large onion, diced",
      "4 cloves garlic, minced",
      "2 tbsp tomato paste",
      "1.5 cups dry red wine (something you'd drink)",
      "1 cup vegetable broth",
      "1 tbsp soy sauce",
      "1 tsp miso paste",
      "Fresh thyme, rosemary, bay leaf",
      "1 cup pearl onions, peeled",
      "2 tbsp olive oil",
      "2 tbsp flour",
      "Salt and pepper",
      "Mashed potatoes or crusty bread for serving",
    ]),
    steps: JSON.stringify([
      "Tear or cut mushrooms into large chunks - don't dice them small. They shrink.",
      "Sear mushrooms in batches in hot olive oil until deeply browned. Don't crowd the pan. Set aside.",
      "In the same pot, saute onion and carrots until softened. Add garlic and tomato paste, cook 2 minutes.",
      "Sprinkle flour over vegetables and stir to coat. Cook 1 minute.",
      "Pour in wine and scrape up all the browned bits. This is the flavor foundation.",
      "Add broth, soy sauce, miso, herbs, and pearl onions. Bring to a simmer.",
      "Return mushrooms to pot. Cover and cook on low for 45 minutes.",
      "Remove lid, increase heat slightly, and cook 15 more minutes until sauce is thick and glossy.",
      "Serve over mashed potatoes or with crusty bread to soak up the sauce.",
    ]),
    notes: "Soy sauce + miso paste gives the umami depth that meat usually provides. Use a wine you'd actually drink - if it tastes bad in a glass, it'll taste bad in the pot.",
  },
  {
    creatorAddress: "0xa102a2cb8AAc6C7d2c477412Ebb7d41d0Ce53495",
    title: "Lemon Blueberry Cake",
    description: "A show-stopping layer cake with fresh blueberries, bright lemon zest, and tangy cream cheese frosting. The kind of cake that ends arguments at potlucks.",
    imageUrl: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&h=600&fit=crop",
    price: 0.75,
    cuisine: "american",
    mealType: "dessert",
    dietaryTags: JSON.stringify(["vegetarian"]),
    prepTime: 30,
    cookTime: 35,
    servings: 12,
    difficulty: "medium",
    ingredients: JSON.stringify([
      "3 1/8 cups cake flour",
      "1 3/4 cups granulated sugar",
      "2 tsp baking powder",
      "1/2 tsp baking soda",
      "1/2 tsp salt",
      "2 1/4 cups unsalted butter (total)",
      "4 large eggs",
      "3/4 cup buttermilk",
      "1/3 cup lemon juice",
      "2 1/2 tsp freshly squeezed lemon juice",
      "2 tbsp lemon zest",
      "2 tsp vanilla extract",
      "2 cups fresh blueberries",
      "20 oz brick style cream cheese",
      "7 1/2 cups powdered sugar",
      "2 tbsp whipping cream",
    ]),
    steps: JSON.stringify([
      "Preheat oven to 350F. Grease and flour two 9-inch round cake pans, line bottoms with parchment.",
      "Whisk together cake flour, granulated sugar, baking powder, baking soda, and salt.",
      "Cut in softened butter and mix until the mixture resembles coarse crumbs.",
      "Whisk eggs, buttermilk, lemon juice, lemon zest, and vanilla extract in a separate bowl.",
      "Pour wet into dry and fold until just combined. Do not overmix.",
      "Gently fold in blueberries. Divide batter evenly between pans.",
      "Bake 30-35 minutes until a toothpick comes out clean. Cool 10 minutes in pans, then turn out onto wire racks.",
      "Make frosting: Beat cream cheese and remaining softened butter until smooth and fluffy.",
      "Gradually add powdered sugar, one cup at a time, beating on low.",
      "Add whipping cream and beat on medium-high until light and spreadable.",
      "Place first layer on stand, frost generously, top with second layer.",
      "Frost top and sides. Garnish with blueberries and lemon zest curls.",
    ]),
    notes: "Toss blueberries in a tablespoon of flour before folding in to prevent sinking. Butter and cream cheese must be room temp for smooth frosting.",
  },
  {
    creatorAddress: "0xa102a2cb8AAc6C7d2c477412Ebb7d41d0Ce53495",
    title: "Perfect Chocolate Chip Cookies",
    description: "Crunchy outside, soft and chewy inside. Brown butter is the move. Makes 8 big cookies that hit different.",
    imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&h=600&fit=crop",
    price: 0.25,
    cuisine: "american",
    mealType: "dessert",
    dietaryTags: JSON.stringify(["vegetarian"]),
    prepTime: 15,
    cookTime: 12,
    servings: 8,
    difficulty: "easy",
    ingredients: JSON.stringify([
      "8 tbsp high-quality butter",
      "1/2 cup white sugar",
      "1/2 cup dark brown sugar",
      "1 large egg",
      "1 tsp vanilla",
      "1/2 tsp kosher salt",
      "1/2 tsp baking soda",
      "1 1/3 cups all-purpose flour",
      "1 cup large chocolate chips",
      "Finishing salt for topping",
    ]),
    steps: JSON.stringify([
      "Melt butter in a light-colored pan over medium heat. Swirl constantly until golden with brown flecks and nutty aroma. Remove immediately.",
      "Combine white sugar, dark brown sugar, browned butter, egg, vanilla, salt, and baking soda in a large bowl.",
      "Mix until ribbon-like consistency - thick, smooth, slightly glossy.",
      "Add flour and mix until just combined.",
      "Fold in chocolate chips.",
      "Scoop into 8 large balls on parchment-lined baking sheet.",
      "Sprinkle each with finishing salt.",
      "Chill 10 minutes or bake immediately at 350F for 10-12 minutes.",
      "Edges should be set and golden, centers slightly underdone.",
      "Cool on sheet 5 minutes. Carryover heat finishes the centers.",
    ]),
    notes: "Brown butter is non-negotiable. Use a light-colored pan so you can see it browning. If dough feels loose, chill it longer.",
  },
  {
    creatorAddress: "0xa102a2cb8AAc6C7d2c477412Ebb7d41d0Ce53495",
    title: "White Chocolate Macadamia Nut Cookies",
    description: "Buttery, nutty, with pools of melted white chocolate. The cookie that proves white chocolate deserves respect.",
    imageUrl: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=800&h=600&fit=crop",
    price: 0.50,
    cuisine: "american",
    mealType: "dessert",
    dietaryTags: JSON.stringify(["vegetarian"]),
    prepTime: 15,
    cookTime: 12,
    servings: 24,
    difficulty: "easy",
    ingredients: JSON.stringify([
      "1 3/4 cups all-purpose flour",
      "1/2 tsp baking powder",
      "1/2 tsp baking soda",
      "1/2 tsp salt",
      "3/4 cup unsalted butter, softened",
      "3/4 cup light brown sugar, packed",
      "1/4 cup granulated white sugar",
      "2 egg yolks",
      "1 tbsp vanilla",
      "1 heaping cup white chocolate chips",
      "1 cup macadamia nuts, roughly chopped",
      "Flaky sea salt for topping",
    ]),
    steps: JSON.stringify([
      "Preheat oven to 350F. Line baking sheets with parchment.",
      "Whisk flour, baking powder, baking soda, and salt. Set aside.",
      "Beat softened butter, brown sugar, and white sugar until light and fluffy, about 3 minutes.",
      "Add egg yolks and vanilla. Beat until smooth.",
      "Add flour mixture and mix on low until just combined.",
      "Fold in white chocolate chips and macadamia nuts by hand.",
      "Scoop rounded tablespoons onto sheets, 2 inches apart.",
      "Bake 10-12 minutes until edges are golden, centers still soft.",
      "Sprinkle with flaky sea salt immediately out of the oven.",
      "Cool on sheet 5 minutes before transferring to wire rack.",
    ]),
    notes: "Egg yolks only (no whites) makes these extra rich and chewy. Roughly chop the macadamias for a mix of chunks and pieces. Flaky salt on top is mandatory.",
  },
];

export async function seedDatabase() {
  // Check if already seeded
  const existing = await db.select().from(creators);
  if (existing.length > 0) {
    return { message: "Database already seeded", count: existing.length };
  }

  // Insert creators
  for (const creator of SAMPLE_CREATORS) {
    await db.insert(creators).values(creator);
  }

  // Insert recipes
  for (const recipe of SAMPLE_RECIPES) {
    await db.insert(recipes).values({
      id: stableId(recipe.title),
      ...recipe,
    });
  }

  return {
    message: "Database seeded",
    creators: SAMPLE_CREATORS.length,
    recipes: SAMPLE_RECIPES.length,
  };
}
